# Generated by Django 5.0.2 on 2024-02-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='media/image/')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField(default=0)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shamba.product')),
            ],
        ),
    ]
