# Generated by Django 5.0.2 on 2024-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
