# Generated by Django 5.0.2 on 2024-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamba', '0004_alter_orderitem_item_item_delete_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('reference_number', models.CharField(max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40000)),
            ],
        ),
    ]
